---

name: Continuous Integration (Elixir)

on:
  push:
    branches:
      - elixir

jobs:
  Elixir:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: elixir
          path: elixir

      - name: Setup (elixir)
        uses: actions/setup-elixir@v1
        with:
          elixir-version: "1.10"
          otp-version: "23.0"

      - name: Dependencies
        run: |
          mix deps.get
          mix compile

      - name: Format
        run: mix format --check-formatted

      - name: Publish
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          event-type: publish
